"""
created: 9/8/2017
(c) copyright 2017 Synacor, Inc

This is a neural network that can take both a small number of words from the subject and body, and
a few features of the e-mail, generated by relationships of the contacts and domains in the address block
to the user account as analytics, as well as any other features that may be useful.
"""
from neon.models.model import Model
from neon.layers import MergeMultistream, LSTM, Affine, RecurrentSum, Tree, BranchNode, SkipNode, Conv, Dropout
from neon.layers import MergeBroadcast
from neon.initializers import GlorotUniform, Kaiming
from neon.optimizers import Adam
from neon.transforms import Softmax, Logistic, Rectlin
from zmlcore.licensed.layers import Noise

class ClassifierNetwork(Model):
    def __init__(self, overlapping_classes=None, exclusive_classes=None, analytics_input=True,
                 network_type='conv_net', num_words=60, width=100, optimizer=Adam()):
        self.width = width
        self.num_words = num_words
        self.overlapping_classes = overlapping_classes
        self.analytics_input = analytics_input
        self.recurrent = network_type == 'lstm'

        # we must have some exclusive classes
        if exclusive_classes is None:
            self.exclusive_classes = ['finance', 'promos', 'social', 'forums', 'updates']
        else:
            self.exclusive_classes = exclusive_classes

        init = GlorotUniform()
        activation = Rectlin(slope=1E-05)
        gate = Logistic()

        input_layers = self.input_layers(analytics_input, init, activation, gate)

        if self.overlapping_classes is None:
            output_layers = [Affine(len(self.exclusive_classes), init, activation=Softmax())]
        else:
            output_branch = BranchNode(name='exclusive_overlapping')
            output_layers = Tree([[SkipNode(),
                                   output_branch,
                                   Affine(20, init, activation=activation),
                                   Affine(len(self.exclusive_classes), init, activation=Softmax())],
                                  [output_branch,
                                   Affine(20, init, activation=activation),
                                   Affine(len(self.overlapping_classes), init, activation=Logistic())]])
        layers = [input_layers,
                  # this is where inputs meet, and where we may want to add depth or
                  # additional functionality
                  # Dropout(keep=0.8),
                  # Affine(80 if self.num_words > 30 else 175, init, activation=activation),
                  Dropout(keep=0.8),
                  output_layers]
        super(ClassifierNetwork, self).__init__(layers, optimizer=optimizer)

    def _epoch_fit(self, dataset, callbacks):
        """
        Just insert ourselves to shuffle the dataset each epoch
        :param dataset:
        :param callbacks:
        :return:
        """
        if hasattr(dataset, 'shuffle'):
            dataset.shuffle()

        return super(ClassifierNetwork, self)._epoch_fit(dataset, callbacks)

    def input_layers(self, analytics_input, init, activation, gate):
        """
        return the input layers. we currently support convolutional and LSTM
        :return:
        """
        if self.recurrent:
            if analytics_input:
                # support analytics + content
                input_layers = MergeMultistream([
                    [LSTM(300, init, init_inner=Kaiming(), activation=activation, gate_activation=gate,
                          reset_cells=True),
                     RecurrentSum()],
                    [Affine(30, init, activation=activation)]],
                    'stack')
            else:
                # content only
                input_layers = [LSTM(300, init, init_inner=Kaiming(), activation=activation, gate_activation=gate,
                                     reset_cells=True),
                                RecurrentSum()]
        else:
            if analytics_input:
                # support analytics + content
                input_layers = MergeMultistream([self.conv_net(activation),
                                                 [Affine(30, init, activation=Logistic())]],
                                                'stack')
            else:
                # content only
                input_layers = self.conv_net(activation)

        return input_layers

    def conv_net(self, activation, init=Kaiming(), version=-1):
        if version == 1:
            return [
                Conv((1, self.width, self.width), padding=0, init=init, activation=activation),
                Conv((3, 1, 150), padding=0, init=init, activation=activation),
                Conv((3, 1, 100), strides={'str_h': 2 if self.num_words > 30 else 1,
                                         'str_w': 1}, padding=0, init=init,
                     activation=activation),
                Conv((3, 1, 150), padding=0, init=init, activation=activation),
                Conv((3, 1, 100), strides={'str_h': 2,
                                          'str_w': 1}, padding=0, init=init,
                     activation=activation),
                Conv((3, 1, 150), padding=0, init=init, activation=activation),
                Conv((3, 1, 100),
                     strides={'str_h': 2, 'str_w': 1}, padding=0, init=init,
                     activation=activation),
                Conv((3, 1, 100),
                     strides={'str_h': 1, 'str_w': 2}, padding=0, init=init,
                     activation=activation),
            ]
        elif version == 2:
            return [
                Conv((1, self.width, self.width), padding=0, init=init, activation=activation),
                Conv((2, 1, 150), padding=0, init=init, activation=activation),
                Conv((2, 1, 150), padding=0, init=init, activation=activation),
                Conv((3, 1, 100), strides={'str_h': 2 if self.num_words > 30 else 1,
                                         'str_w': 1}, padding=0, init=init,
                     activation=activation),
                Conv((3, 1, 150), padding=0, init=init, activation=activation),
                Conv((3, 1, 100), strides={'str_h': 2,
                                          'str_w': 1}, padding=0, init=init,
                     activation=activation),
                Conv((3, 1, 150), padding=0, init=init, activation=activation),
                Conv((3, 1, 100),
                     strides={'str_h': 2, 'str_w': 1}, padding=0, init=init,
                     activation=activation),
                Conv((3, 1, 100),
                     strides={'str_h': 1, 'str_w': 2}, padding=0, init=init,
                     activation=activation),
            ]
        elif version == 3:
            return [
                Conv((1, self.width, self.width), padding=0, init=init, activation=activation),
                Conv((2, 1, 150), padding=0, init=init, activation=activation),
                Conv((2, 1, 150), padding=0, init=init, activation=activation),
                Conv((3, 1, 100), strides={'str_h': 2 if self.num_words > 30 else 1,
                                         'str_w': 1}, padding=0, init=init,
                     activation=activation),
                Conv((2, 1, 150), padding=0, init=init, activation=activation),
                Conv((2, 1, 150), padding=0, init=init, activation=activation),
                Conv((3, 1, 100), strides={'str_h': 2,
                                          'str_w': 1}, padding=0, init=init,
                     activation=activation),
                Conv((2, 1, 150), padding=0, init=init, activation=activation),
                Conv((2, 1, 150), padding=0, init=init, activation=activation),
                Conv((3, 1, 100),
                     strides={'str_h': 2, 'str_w': 1}, padding=0, init=init,
                     activation=activation),
                Conv((3, 1, 100),
                     strides={'str_h': 1, 'str_w': 2}, padding=0, init=init,
                     activation=activation),
            ]
        elif version == 4:
            return [
                Conv((1, self.width, self.width), padding=0, init=init, activation=activation),
                Conv((2, 1, 150), padding=0, init=init, activation=activation),
                Conv((2, 1, 150), padding=0, init=init, activation=activation),
                Conv((3, 1, 100), strides={'str_h': 2 if self.num_words > 30 else 1,
                                         'str_w': 1}, padding=0, init=init,
                     activation=activation),
                Conv((2, 1, 150), padding=0, init=init, activation=activation),
                Conv((2, 1, 150), padding=0, init=init, activation=activation),
                Conv((3, 1, 100), strides={'str_h': 2,
                                          'str_w': 1}, padding=0, init=init,
                     activation=activation),
                Conv((3, 1, 150), padding=0, init=init, activation=activation),
                Conv((3, 1, 100),
                     strides={'str_h': 2, 'str_w': 1}, padding=0, init=init,
                     activation=activation),
                Conv((3, 1, 100),
                     strides={'str_h': 1, 'str_w': 2}, padding=0, init=init,
                     activation=activation),
            ]
        elif version == 5:
            return [
                Conv((1, self.width, self.width), padding=0, init=init, activation=activation),
                Conv((3, 1, 150), padding=0, init=init, activation=activation),
                Conv((5, 1, 150), padding=2, init=init, activation=activation),
                Conv((3, 1, 100), strides={'str_h': 2 if self.num_words > 30 else 1,
                                         'str_w': 1}, padding=0, init=init,
                     activation=activation),
                Conv((3, 1, 150), padding=0, init=init, activation=activation),
                Conv((3, 1, 100), strides={'str_h': 2,
                                          'str_w': 1}, padding=0, init=init,
                     activation=activation),
                Conv((3, 1, 150), padding=0, init=init, activation=activation),
                Conv((3, 1, 100),
                     strides={'str_h': 2, 'str_w': 1}, padding=0, init=init,
                     activation=activation),
                Conv((3, 1, 100),
                     strides={'str_h': 1, 'str_w': 2}, padding=0, init=init,
                     activation=activation),
            ]
        elif version == 6: # stored backup best model
            return [
                Conv((1, self.width, self.width), padding=0, init=init, activation=activation),
                Conv((3, 1, 150), padding=0, init=init, activation=activation),
                Conv((3, 1, 100), strides={'str_h': 2 if self.num_words > 30 else 1,
                                         'str_w': 1}, padding=0, init=init,
                     activation=activation),
                Conv((3, 1, 150), padding=0, init=init, activation=activation),
                Conv((3, 1, 100), strides={'str_h': 2,
                                          'str_w': 1}, padding=0, init=init,
                     activation=activation),
                Conv((3, 1, 150), padding=0, init=init, activation=activation),
                Conv((3, 1, 100),
                     strides={'str_h': 2, 'str_w': 1}, padding=0, init=init,
                     activation=activation),
                Conv((3, 1, 100),
                     strides={'str_h': 1, 'str_w': 2}, padding=0, init=init,
                     activation=activation),
            ]
        elif version == 7: # strong
            return [
                Conv((1, self.width, self.width), padding=0, init=init, activation=activation),
                Conv((3, 1, 200), padding=0, init=init, activation=activation),
                Conv((3, 1, 100), strides={'str_h': 2 if self.num_words > 30 else 1,
                                         'str_w': 1}, padding=0, init=init,
                     activation=activation),
                Conv((3, 1, 80), padding=0, init=init, activation=activation),
                Conv((3, 1, 64), strides={'str_h': 2,
                                          'str_w': 1}, padding=0, init=init,
                     activation=activation),
                Conv((3, 1, 64), padding=0, init=init, activation=activation),
                Conv((3, 1, 64),
                     strides={'str_h': 2, 'str_w': 1}, padding=0, init=init,
                     activation=activation),
                Conv((3, 1, 64),
                     strides={'str_h': 1, 'str_w': 2}, padding=0, init=init,
                     activation=activation),
            ]
        elif version == 8: # stronger
            return [
                Conv((1, self.width, self.width), padding=0, init=init, activation=activation),
                Conv((3, 1, 100), padding=0, init=init, activation=activation),
                Conv((3, 1, 80), strides={'str_h': 2 if self.num_words > 30 else 1,
                                         'str_w': 1}, padding=0, init=init,
                     activation=activation),
                Conv((3, 1, 64), padding=0, init=init, activation=activation),
                Conv((3, 1, 64), strides={'str_h': 2,
                                          'str_w': 1}, padding=0, init=init,
                     activation=activation),
                Conv((3, 1, 64), padding=0, init=init, activation=activation),
                Conv((3, 1, 64),
                     strides={'str_h': 2, 'str_w': 1}, padding=0, init=init,
                     activation=activation),
                Conv((3, 1, 64),
                     strides={'str_h': 1, 'str_w': 2}, padding=0, init=init,
                     activation=activation),
            ]
        elif version == 9: # stronger, but still can't beat the best # 6
            return [
                Conv((1, self.width, self.width), padding=0, init=init, activation=activation),
                Conv((3, 1, 100), padding=0, init=init, activation=activation),
                Conv((3, 1, 80), strides={'str_h': 2 if self.num_words > 30 else 1,
                                         'str_w': 1}, padding=0, init=init,
                     activation=activation),
                Conv((3, 1, 100), padding=0, init=init, activation=activation),
                Conv((3, 1, 80), strides={'str_h': 2,
                                          'str_w': 1}, padding=0, init=init,
                     activation=activation),
                Conv((3, 1, 100), padding=0, init=init, activation=activation),
                Conv((3, 1, 80),
                     strides={'str_h': 2, 'str_w': 1}, padding=0, init=init,
                     activation=activation),
                Conv((3, 1, 80),
                     strides={'str_h': 1, 'str_w': 2}, padding=0, init=init,
                     activation=activation),
            ]
        elif version == 10: # best pct 20.8% epoch 8, .70 log loss glove.6B.300d.txt
            return [
                Conv((1, self.width, self.width), padding=0, init=init, activation=activation),
                Conv((3, 1, 150), padding=0, init=init, activation=activation),
                Dropout(keep=0.9),
                Conv((3, 1, 100), strides={'str_h': 2 if self.num_words > 30 else 1,
                                         'str_w': 1}, padding=0, init=init,
                     activation=activation),
                Conv((3, 1, 150), padding=0, init=init, activation=activation),
                Dropout(keep=0.9),
                Conv((3, 1, 100), strides={'str_h': 2,
                                          'str_w': 1}, padding=0, init=init,
                     activation=activation),
                Conv((3, 1, 120), padding=0, init=init, activation=activation),
                Conv((3, 1, 80),
                     strides={'str_h': 2, 'str_w': 1}, padding=0, init=init,
                     activation=activation),
                Conv((3, 1, 80),
                     strides={'str_h': 1, 'str_w': 2}, padding=0, init=init,
                     activation=activation),
            ]
        elif version == 11:
            return [
                Conv((1, self.width, self.width), padding=0, init=init, activation=activation),
                Conv((3, 1, 150), padding=0, init=init, activation=activation),
                Dropout(keep=0.8),
                Conv((3, 1, 100), strides={'str_h': 2 if self.num_words > 30 else 1,
                                           'str_w': 1}, padding=0, init=init,
                     activation=activation),
                Conv((3, 1, 150), padding=0, init=init, activation=activation),
                Dropout(keep=0.9),
                Conv((3, 1, 100), strides={'str_h': 2,
                                           'str_w': 1}, padding=0, init=init,
                     activation=activation),
                Conv((3, 1, 150), padding=0, init=init, activation=activation),
                Conv((3, 1, 100),
                     strides={'str_h': 2, 'str_w': 1}, padding=0, init=init,
                     activation=activation),
                Conv((3, 1, 100),
                     strides={'str_h': 1, 'str_w': 1}, padding=0, init=init,
                     activation=activation),
            ]
        elif version == 12: # best logloss 0.55, epoch 5, 21.4% misclass
            return [
                Conv((1, self.width, self.width), padding=0, init=init, activation=activation),
                Conv((2, 1, 150), padding=0, init=init, activation=activation),
                Dropout(keep=0.9),
                Conv((4, 1, 100), strides={'str_h': 2 if self.num_words > 30 else 1,
                                           'str_w': 1}, padding=0, init=init,
                     activation=activation),
                Conv((3, 1, 150), padding=0, init=init, activation=activation),
                Dropout(keep=0.9),
                Conv((3, 1, 100), strides={'str_h': 2,
                                           'str_w': 1}, padding=0, init=init,
                     activation=activation),
                Conv((3, 1, 150), padding=0, init=init, activation=activation),
                Conv((3, 1, 100),
                     strides={'str_h': 2, 'str_w': 1}, padding=0, init=init,
                     activation=activation),
                Conv((3, 1, 100),
                     strides={'str_h': 1, 'str_w': 1}, padding=0, init=init,
                     activation=activation),
            ]
        elif version == 13: # best logloss 0.54, epoch 5, 20.3 misclass
            return [
                Conv((1, self.width, self.width), padding=0, init=init, activation=activation),
                Conv((2, 1, 150), padding=0, init=init, activation=activation),
                Dropout(keep=0.9),
                Conv((4, 1, 110), strides={'str_h': 2 if self.num_words > 30 else 1,
                                         'str_w': 1}, padding=0, init=init,
                     activation=activation),
                Conv((2, 1, 150), padding=0, init=init, activation=activation),
                Dropout(keep=0.9),
                Conv((4, 1, 100), strides={'str_h': 2,
                                          'str_w': 1}, padding=0, init=init,
                     activation=activation),
                Conv((2, 1, 150), padding=0, init=init, activation=activation),
                Dropout(keep=0.9),
                Conv((4, 1, 100),
                     strides={'str_h': 2, 'str_w': 1}, padding=0, init=init,
                     activation=activation),
                Conv((3, 1, 80),
                     strides={'str_h': 1, 'str_w': 1}, padding=0, init=init,
                     activation=activation),
            ]
        elif version == 14: # best logloss 0.53, epoch 5, 21.4 misclass
            return [
                Conv((1, self.width, self.width), padding=0, init=init, activation=activation),
                Conv((2, 1, 150), padding=0, init=init, activation=activation),
                Dropout(keep=0.9),
                Conv((4, 1, 100), strides={'str_h': 2 if self.num_words > 30 else 1,
                                         'str_w': 1}, padding=0, init=init,
                     activation=activation),
                Conv((2, 1, 150), padding=0, init=init, activation=activation),
                Dropout(keep=0.9),
                Conv((4, 1, 100), strides={'str_h': 2,
                                          'str_w': 1}, padding=0, init=init,
                     activation=activation),
                Conv((2, 1, 150), padding=0, init=init, activation=activation),
                Dropout(keep=0.9),
                Conv((4, 1, 100),
                     strides={'str_h': 2, 'str_w': 1}, padding=0, init=init,
                     activation=activation),
                Conv((3, 1, 100),
                     strides={'str_h': 1, 'str_w': 1}, padding=0, init=init,
                     activation=activation),
            ]
        elif version == 15:
            return [
                Conv((1, self.width, self.width), padding=0, init=init, activation=activation),
                Conv((2, 1, 150), padding=0, init=init, activation=activation),
                Dropout(keep=0.9),
                Conv((4, 1, 120), strides={'str_h': 2 if self.num_words > 30 else 1,
                                         'str_w': 1}, padding=0, init=init,
                     activation=activation),
                Conv((2, 1, 150), padding=0, init=init, activation=activation),
                Dropout(keep=0.9),
                Conv((4, 1, 120), strides={'str_h': 2,
                                          'str_w': 1}, padding=0, init=init,
                     activation=activation),
                Conv((2, 1, 150), padding=0, init=init, activation=activation),
                Dropout(keep=0.9),
                Conv((4, 1, 120),
                     strides={'str_h': 2, 'str_w': 1}, padding=0, init=init,
                     activation=activation),
                Conv((3, 1, 100),
                     strides={'str_h': 1, 'str_w': 1}, padding=0, init=init,
                     activation=activation),
            ]
        elif version == 16:
            return [
                Conv((1, self.width, self.width), padding=0, init=init, activation=activation),
                Conv((2, 1, 150), padding=0, init=init, activation=activation),
                Dropout(keep=0.9),
                Conv((4, 1, 100), strides={'str_h': 2 if self.num_words > 30 else 1,
                                           'str_w': 1}, padding=0, init=init,
                     activation=activation),
                Conv((2, 1, 150), padding=0, init=init, activation=activation),
                Dropout(keep=0.9),
                Conv((4, 1, 100), strides={'str_h': 2, 'str_w': 1}, padding=0, init=init, activation=activation),
                Conv((3, 1, 150), padding=0, init=init, activation=activation),
                Dropout(keep=0.9),
                Conv((3, 1, 100), strides={'str_h': 2, 'str_w': 1}, padding=0, init=init, activation=activation),
                Conv((3, 1, 100), strides={'str_h': 1, 'str_w': 1}, padding=0, init=init, activation=activation),
            ]
        elif version == 17: # best logloss 0.52 epoch 4, 20.9% misclass
            return [
                Conv((1, self.width, self.width), padding=0, init=init, activation=activation),
                Conv((2, 1, 150), padding=0, init=init, activation=activation),
                Dropout(keep=0.9),
                Conv((4, 1, 100), strides={'str_h': 2 if self.num_words > 30 else 1,
                                           'str_w': 1}, padding=0, init=init,
                     activation=activation),
                Conv((2, 1, 150), padding=0, init=init, activation=activation),
                Dropout(keep=0.9),
                Conv((4, 1, 100), strides={'str_h': 2, 'str_w': 1}, padding=0, init=init, activation=activation),
                Conv((2, 1, 150), padding=0, init=init, activation=activation),
                Dropout(keep=0.9),
                Conv((7, 1, 100), strides={'str_h': 2, 'str_w': 1}, padding=0, init=init, activation=activation),
                # Conv((3, 1, 100), strides={'str_h': 1, 'str_w': 1}, padding=0, init=init, activation=activation),
            ]
        elif version == 18: # not good
            return [
                Conv((1, self.width, self.width), padding=0, init=init, activation=activation),
                Conv((2, 1, 150), padding=0, init=init, activation=activation),
                Dropout(keep=0.9),
                Conv((5, 1, 100), strides={'str_h': 2 if self.num_words > 30 else 1,
                                           'str_w': 1}, padding=0, init=init,
                     activation=activation),
                Conv((2, 1, 150), padding=0, init=init, activation=activation),
                Dropout(keep=0.9),
                Conv((5, 1, 100), strides={'str_h': 2, 'str_w': 1}, padding=0, init=init, activation=activation),
                Conv((2, 1, 150), padding=0, init=init, activation=activation),
                Dropout(keep=0.9),
                Conv((5, 1, 100), strides={'str_h': 2, 'str_w': 1}, padding=0, init=init, activation=activation),
            ]
        elif version == 19: # strong logloss 0.55, epoch 5, 21.6% misclass, 0.56, epoch 6, 20.8 misclass
            return [
                Conv((1, self.width, self.width), padding=0, init=init, activation=activation),
                Conv((2, 1, 100), padding=0, init=init, activation=activation),
                Dropout(keep=0.9),
                Conv((4, 1, 100), strides={'str_h': 2 if self.num_words > 30 else 1,
                                           'str_w': 1}, padding=0, init=init,
                     activation=activation),
                Conv((2, 1, 150), padding=0, init=init, activation=activation),
                Dropout(keep=0.9),
                Conv((4, 1, 100), strides={'str_h': 2, 'str_w': 1}, padding=0, init=init, activation=activation),
                Conv((2, 1, 150), padding=0, init=init, activation=activation),
                Dropout(keep=0.9),
                Conv((7, 1, 100), strides={'str_h': 2, 'str_w': 1}, padding=0, init=init, activation=activation),
            ]
        elif version == 20: # best logloss 0.51, epoch 6, 19.2% misclass, regressed as if overtrained at epoch 4,
            # epochs 6-9, .51, .52, .59, .58 logloss, 19.2, 20, 20, 19.7 misclass
            return [
                Conv((1, self.width, self.width), padding=0, init=init, activation=activation),
                Conv((2, 1, 100), padding=0, init=init, activation=activation),
                Dropout(keep=0.9),
                Conv((4, 1, 150), strides={'str_h': 2 if self.num_words > 30 else 1,
                                           'str_w': 1}, padding=0, init=init,
                     activation=activation),
                Conv((2, 1, 100), padding=0, init=init, activation=activation),
                Dropout(keep=0.9),
                Conv((4, 1, 150), strides={'str_h': 2, 'str_w': 1}, padding=0, init=init, activation=activation),
                Conv((2, 1, 100), padding=0, init=init, activation=activation),
                Dropout(keep=0.9),
                Conv((7, 1, 100), strides={'str_h': 2, 'str_w': 1}, padding=0, init=init, activation=activation),
            ]
        elif version == 21: # not great
            return [
                Conv((1, self.width, self.width), padding=0, init=init, activation=activation),
                Conv((2, 1, 150), padding=0, init=init, activation=activation),
                Dropout(keep=0.9),
                Conv((4, 1, 80), strides={'str_h': 2 if self.num_words > 30 else 1,
                                           'str_w': 1}, padding=0, init=init,
                     activation=activation),
                Conv((2, 1, 150), padding=0, init=init, activation=activation),
                Dropout(keep=0.9),
                Conv((4, 1, 80), strides={'str_h': 2, 'str_w': 1}, padding=0, init=init, activation=activation),
                Conv((2, 1, 150), padding=0, init=init, activation=activation),
                Dropout(keep=0.9),
                Conv((7, 1, 80), strides={'str_h': 2, 'str_w': 1}, padding=0, init=init, activation=activation),
            ]
        elif version == 22: # best logloss 0.51, epoch 6, 19.8% misclass, small regression epoch 5
            return [
                Conv((1, self.width, self.width), padding=0, init=init, activation=activation),
                Conv((2, 1, 100), padding=0, init=init, activation=activation),
                Dropout(keep=0.9),
                Conv((4, 1, 150), strides={'str_h': 2 if self.num_words > 30 else 1,
                                           'str_w': 1}, padding=0, init=init, activation=activation),
                Conv((2, 1, 100), padding=0, init=init, activation=activation),
                Dropout(keep=0.9),
                Conv((4, 1, 150), strides={'str_h': 2, 'str_w': 1}, padding=0, init=init, activation=activation),
                Conv((2, 1, 100), padding=0, init=init, activation=activation),
                Dropout(keep=0.9),
                Conv((7, 1, 150), strides={'str_h': 2, 'str_w': 1}, padding=0, init=init, activation=activation),
            ]
        elif version == 23:
            return [
                Conv((1, self.width, self.width), padding=0, init=init, activation=activation),
                Dropout(keep=0.9),
                Conv((2, 1, 100), padding=0, init=init, activation=activation),
                Dropout(keep=0.9),
                Conv((4, 1, 150), strides={'str_h': 2 if self.num_words > 30 else 1,
                                           'str_w': 1}, padding=0, init=init, activation=activation),
                Dropout(keep=0.9),
                Conv((2, 1, 100), padding=0, init=init, activation=activation),
                Dropout(keep=0.9),
                Conv((4, 1, 150), strides={'str_h': 2, 'str_w': 1}, padding=0, init=init, activation=activation),
                Dropout(keep=0.9),
                Conv((2, 1, 100), padding=0, init=init, activation=activation),
                Dropout(keep=0.9),
                Conv((7, 1, 150), strides={'str_h': 2, 'str_w': 1}, padding=0, init=init, activation=activation),
            ]
        elif version == 24: # best logloss 0.51, epoch 8, 19.2% misclass, very small regression epoch 7
            # epoch 9: logloss 0.52, 18.8% misclass
            return [
                Conv((1, self.width, self.width), padding=0, init=init, activation=activation),
                Dropout(keep=0.9),
                Conv((2, 1, 100), padding=0, init=init, activation=activation),
                Dropout(keep=0.9),
                Conv((4, 1, 150), strides={'str_h': 2 if self.num_words > 30 else 1,
                                           'str_w': 1}, padding=0, init=init, activation=activation),
                Dropout(keep=0.9),
                Conv((2, 1, 100), padding=0, init=init, activation=activation),
                Dropout(keep=0.9),
                Conv((4, 1, 150), strides={'str_h': 2, 'str_w': 1}, padding=0, init=init, activation=activation),
                Dropout(keep=0.9),
                Conv((2, 1, 100), padding=0, init=init, activation=activation),
                Dropout(keep=0.9),
                Conv((7, 1, 100), strides={'str_h': 2, 'str_w': 1}, padding=0, init=init, activation=activation),
            ]
        elif version == 25: # best logloss 0.48, epoch 7, 18.4% misclass
            # w/intermediate layer between inputs and outputs removed
            return [
                Conv((1, self.width, self.width), padding=0, init=init, activation=activation),
                Dropout(keep=0.9),
                Conv((2, 1, 100), padding=0, init=init, activation=activation),
                Dropout(keep=0.9),
                Conv((4, 1, 150), strides={'str_h': 2 if self.num_words > 30 else 1,
                                           'str_w': 1}, padding=0, init=init, activation=activation),
                Dropout(keep=0.9),
                Conv((2, 1, 100), padding=0, init=init, activation=activation),
                Dropout(keep=0.9),
                Conv((4, 1, 150), strides={'str_h': 2, 'str_w': 1}, padding=0, init=init, activation=activation),
                Dropout(keep=0.9),
                Conv((2, 1, 100), padding=0, init=init, activation=activation),
                Dropout(keep=0.9),
                Conv((7, 1, 80), strides={'str_h': 2, 'str_w': 1}, padding=0, init=init, activation=activation),
            ]
        elif version == 26: # best logloss 0.47, epoch 6, 19.1% misclass, so not best misclass
            return [
                Conv((1, self.width, self.width), padding=0, init=init, activation=activation),
                Dropout(keep=0.9),
                Conv((2, 1, 100), padding=0, init=init, activation=activation),
                Dropout(keep=0.9),
                Conv((4, 1, 150), strides={'str_h': 2 if self.num_words > 30 else 1,
                                           'str_w': 1}, padding=0, init=init, activation=activation),
                Dropout(keep=0.9),
                Conv((2, 1, 100), padding=0, init=init, activation=activation),
                Dropout(keep=0.9),
                Conv((4, 1, 80), strides={'str_h': 2, 'str_w': 1}, padding=0, init=init, activation=activation),
                Dropout(keep=0.9),
                Conv((2, 1, 100), padding=0, init=init, activation=activation),
                Dropout(keep=0.9),
                Conv((7, 1, 80), strides={'str_h': 2, 'str_w': 1}, padding=0, init=init, activation=activation),
            ]
        elif version == 27: # best logloss 0.47, epoch 8 & 9, 18.5% misclass, almost best misclass
            return [
                Conv((1, self.width, self.width), padding=0, init=init, activation=activation),
                Dropout(keep=0.8),
                Conv((2, 1, 100), padding=0, init=init, activation=activation),
                Dropout(keep=0.9),
                Conv((4, 1, 150), strides={'str_h': 2 if self.num_words > 30 else 1,
                                           'str_w': 1}, padding=0, init=init, activation=activation),
                Dropout(keep=0.9),
                Conv((2, 1, 100), padding=0, init=init, activation=activation),
                Dropout(keep=0.9),
                Conv((4, 1, 150), strides={'str_h': 2, 'str_w': 1}, padding=0, init=init, activation=activation),
                Dropout(keep=0.9),
                Conv((2, 1, 100), padding=0, init=init, activation=activation),
                Dropout(keep=0.9),
                Conv((7, 1, 80), strides={'str_h': 2, 'str_w': 1}, padding=0, init=init, activation=activation),
            ]
        elif version == 28: # looks like an excellent direction, but need to fix memory leak in neon
            # before it's practical. likely needs more channel dimensions and variation
            return [
                Conv((1, self.width, self.width), padding=0, init=init, activation=activation),
                Dropout(keep=0.9),
                MergeBroadcast([
                    [
                        Conv((2, 1, 50), padding=1, init=init, activation=activation),
                        Dropout(keep=0.9),
                        Conv((2, 1, 50), padding=0, init=init, activation=activation),
                        Dropout(keep=0.9),
                        Conv((3, 1, 50), strides={'str_h': 2, 'str_w': 1}, padding=1, init=init,
                             activation=activation),
                        Dropout(keep=0.9),
                        Conv((4, 1, 50), strides={'str_h': 2, 'str_w': 1}, padding=1, init=init,
                             activation=activation),
                        Dropout(keep=0.9),
                        Conv((7, 1, 50), strides={'str_h': 2, 'str_w': 1}, padding=1, init=init,
                             activation=activation)
                    ],
                    [
                        Conv((3, 1, 50), padding=1, init=init, activation=activation),
                        Dropout(keep=0.9),
                        Conv((3, 1, 50), strides={'str_h': 2, 'str_w': 1}, padding=1, init=init,
                             activation=activation),
                        Dropout(keep=0.9),
                        Conv((4, 1, 50), strides={'str_h': 2, 'str_w': 1}, padding=1, init=init,
                             activation=activation),
                        Dropout(keep=0.9),
                        Conv((7, 1, 50), strides={'str_h': 2, 'str_w': 1}, padding=1, init=init,
                             activation=activation)
                    ],
                    [
                        Conv((4, 1, 50), padding=2, init=init, activation=activation),
                        Dropout(keep=0.9),
                        Conv((4, 1, 50), padding=0, init=init, activation=activation),
                        Dropout(keep=0.9),
                        Conv((3, 1, 50), strides={'str_h': 2, 'str_w': 1}, padding=1, init=init,
                             activation=activation),
                        Dropout(keep=0.9),
                        Conv((4, 1, 50), strides={'str_h': 2, 'str_w': 1}, padding=1, init=init,
                             activation=activation),
                        Dropout(keep=0.9),
                        Conv((7, 1, 50), strides={'str_h': 2, 'str_w': 1}, padding=1, init=init,
                             activation=activation)
                    ]
                ], 'stack'),
            ]
        elif version == 29:  # strong logloss 0.45, epoch 6, 18.8% misclass, possibly inconsistent
            # logloss 0.45, epoch 7, 17.9% misclass
            # logloss 0.44, epoch 8, 17.6% misclass
            # logloss 0.45, epoch 9, 18.0% misclass
            # logloss 0.44, epoch 10, 17.3% misclass, then overtrain
            return [
                Conv((1, self.width, self.width), padding=0, init=init, activation=activation),
                Dropout(keep=0.875),
                Conv((2, 1, 100), padding=0, init=init, activation=activation),
                Dropout(keep=0.92),
                Conv((4, 1, 150), strides={'str_h': 2 if self.num_words > 59 else 1,
                                           'str_w': 1}, padding=0, init=init, activation=activation),
                Dropout(keep=0.9),
                Conv((2, 1, 100), padding=0, init=init, activation=activation),
                Dropout(keep=0.9),
                Conv((4, 1, 150), strides={'str_h': 2, 'str_w': 1}, padding=0, init=init, activation=activation),
                Dropout(keep=0.9),
                Conv((2, 1, 100), padding=0, init=init, activation=activation),
                Dropout(keep=0.9),
                Conv((7, 1, 80), strides={'str_h': 2, 'str_w': 1}, padding=0, init=init, activation=activation),
            ]
        elif version == 30: # best logloss 0.45, epoch 13, 17.1% misclass
            # too large of a memory leak on neon cpu backend
            return [
                Conv((1, self.width, self.width), padding=0, init=init, activation=activation),
                Dropout(keep=0.875),
                Conv((2, 1, 100), padding=1, init=init, activation=activation),
                Dropout(keep=0.9),
                Conv((3, 1, 100), padding=1, init=init, activation=activation),
                Dropout(keep=0.9),
                Conv((4, 1, 100), padding=1, init=init, activation=activation),
                Dropout(keep=0.9),
                Conv((3, 1, 100), strides={'str_h': 2, 'str_w': 1}, padding=1, init=init,
                     activation=activation),
                Dropout(keep=0.9),
                Conv((5, 1, 100), strides={'str_h': 2, 'str_w': 1}, padding=1, init=init,
                     activation=activation),
                Dropout(keep=0.9),
                Conv((7, 1, 100), strides={'str_h': 2, 'str_w': 1}, padding=1, init=init,
                     activation=activation)
            ]
        elif version == 31: # not great
            return [
                Conv((1, self.width, self.width), padding=0, init=init, activation=activation),
                Dropout(keep=0.875),
                Conv((2, 1, 100), padding=1, init=init, activation=activation),
                Dropout(keep=0.9),
                Conv((4, 1, 100), padding=1, init=init, activation=activation),
                Dropout(keep=0.9),
                Conv((5, 1, 100), strides={'str_h': 2, 'str_w': 1}, padding=0, init=init,
                     activation=activation),
                Dropout(keep=0.9),
                Conv((3, 1, 100), padding=0, init=init, activation=activation),
                Dropout(keep=0.9),
                Conv((5, 1, 100), strides={'str_h': 2, 'str_w': 1}, padding=0, init=init,
                     activation=activation),
                Dropout(keep=0.9),
                Conv((7, 1, 100), strides={'str_h': 2, 'str_w': 1}, padding=0, init=init,
                     activation=activation)
            ]
        elif version == 32:
            return [
                Conv((1, self.width, self.width), padding=0, init=init, activation=activation),
                Dropout(keep=0.875),
                Conv((2, 1, 100), padding=1, init=init, activation=activation),
                Dropout(keep=0.92),
                Conv((4, 1, 150), strides={'str_h': 2 if self.num_words > 59 else 1,
                                           'str_w': 1}, padding=1, init=init, activation=activation),
                Dropout(keep=0.9),
                Conv((2, 1, 100), padding=1, init=init, activation=activation),
                Dropout(keep=0.9),
                Conv((4, 1, 150), strides={'str_h': 2, 'str_w': 1}, padding=1, init=init, activation=activation),
                Dropout(keep=0.9),
                Conv((5, 1, 100), padding=0, init=init, activation=activation),
                Dropout(keep=0.9),
                Conv((7, 1, 80), strides={'str_h': 2, 'str_w': 1}, padding=0, init=init, activation=activation),
            ]
        elif version == 33:
            return [
                Conv((1, self.width, self.width), padding=0, init=init, activation=activation),
                Dropout(keep=0.9),
                Conv((2, 1, 80), padding=1, init=init, activation=activation),
                Dropout(keep=0.9),
                Conv((4, 1, 100), strides={'str_h': 2 if self.num_words > 59 else 1,
                                           'str_w': 1}, padding=1, init=init, activation=activation),
                Dropout(keep=0.9),
                Conv((2, 1, 100), padding=1, init=init, activation=activation),
                Dropout(keep=0.9),
                Conv((4, 1, 100), strides={'str_h': 2, 'str_w': 1}, padding=1, init=init, activation=activation),
                Dropout(keep=0.9),
                Conv((5, 1, 100), padding=0, init=init, activation=activation),
                Dropout(keep=0.9),
                Conv((7, 1, 80), strides={'str_h': 2, 'str_w': 1}, padding=0, init=init, activation=activation),
            ]
        elif version == 34:
            return [
                Conv((1, self.width, self.width), padding=0, init=init, activation=activation),
                Dropout(keep=0.875),
                Conv((2, 1, 120), padding=1, init=init, activation=activation),
                Dropout(keep=0.9),
                Conv((4, 1, 100), strides={'str_h': 2 if self.num_words > 59 else 1,
                                           'str_w': 1}, padding=1, init=init, activation=activation),
                Dropout(keep=0.9),
                Conv((3, 1, 100), padding=1, init=init, activation=activation),
                Dropout(keep=0.9),
                Conv((4, 1, 100), strides={'str_h': 2, 'str_w': 1}, padding=1, init=init, activation=activation),
                Dropout(keep=0.9),
                Conv((5, 1, 100), padding=0, init=init, activation=activation),
                Dropout(keep=0.9),
                Conv((6, 1, 80), strides={'str_h': 2, 'str_w': 1}, padding=0, init=init, activation=activation),
            ]
        elif version == 35:
            return [
                Conv((1, self.width, self.width), padding=0, init=init, activation=activation),
                Dropout(keep=0.9),
                Conv((2, 1, 100), padding=1, init=init, activation=activation),
                Dropout(keep=0.9),
                Conv((4, 1, 100), strides={'str_h': 2 if self.num_words > 59 else 1,
                                           'str_w': 1}, padding=1, init=init, activation=activation),
                Dropout(keep=0.9),
                Conv((2, 1, 100), padding=1, init=init, activation=activation),
                Dropout(keep=0.9),
                Conv((4, 1, 100), strides={'str_h': 2, 'str_w': 1}, padding=1, init=init, activation=activation),
                Dropout(keep=0.9),
                Conv((3, 1, 100), padding=0, init=init, activation=activation),
                Dropout(keep=0.9),
                Conv((7, 1, 80), strides={'str_h': 2, 'str_w': 1}, padding=0, init=init, activation=activation),
            ]
        elif version == 36:
            return [
                Conv((1, self.width, self.width), padding=0, init=init, activation=activation),
                Dropout(keep=0.9),
                Conv((2, 1, 100), padding=1, init=init, activation=activation),
                Dropout(keep=0.9),
                Conv((3, 1, 100), strides={'str_h': 2 if self.num_words > 59 else 1,
                                           'str_w': 1}, padding=1, init=init, activation=activation),
                Dropout(keep=0.9),
                Conv((2, 1, 100), padding=1, init=init, activation=activation),
                Dropout(keep=0.9),
                Conv((3, 1, 100), strides={'str_h': 2, 'str_w': 1}, padding=1, init=init, activation=activation),
                Dropout(keep=0.9),
                Conv((5, 1, 100), padding=0, init=init, activation=activation),
                Dropout(keep=0.9),
                Conv((7, 1, 80), strides={'str_h': 2, 'str_w': 1}, padding=0, init=init, activation=activation),
            ]
        elif version == 37:
            return [
                Conv((1, self.width, self.width), padding=0, init=init, activation=activation),
                Dropout(keep=0.9),
                Conv((2, 1, 100), padding=1, init=init, activation=activation),
                Dropout(keep=0.9),
                Conv((4, 1, 100), strides={'str_h': 2 if self.num_words > 59 else 1,
                                           'str_w': 1}, padding=1, init=init, activation=activation),
                Dropout(keep=0.9),
                Conv((2, 1, 100), padding=1, init=init, activation=activation),
                Dropout(keep=0.9),
                Conv((4, 1, 100), strides={'str_h': 2, 'str_w': 1}, padding=1, init=init, activation=activation),
                Dropout(keep=0.9),
                Conv((3, 1, 100), padding=0, init=init, activation=activation),
                Dropout(keep=0.9),
                Conv((4, 1, 80), strides={'str_h': 2, 'str_w': 1}, padding=0, init=init, activation=activation),
            ]
        elif version == 38:
            return [
                Conv((1, self.width, self.width), padding=0, init=init, activation=activation),
                Dropout(keep=0.875),
                Conv((2, 1, 100), padding=1, init=init, activation=activation),
                Dropout(keep=0.9),
                Conv((3, 1, 80), padding=1, init=init, activation=activation),
                Dropout(keep=0.9),
                Conv((4, 1, 60), padding=1, init=init, activation=activation),
                Dropout(keep=0.9),
                Conv((3, 1, 100), strides={'str_h': 2, 'str_w': 1}, padding=1, init=init,
                     activation=activation),
                Dropout(keep=0.9),
                Conv((5, 1, 100), strides={'str_h': 2, 'str_w': 1}, padding=1, init=init,
                     activation=activation),
                Dropout(keep=0.9),
                Conv((7, 1, 100), strides={'str_h': 2, 'str_w': 1}, padding=1, init=init,
                     activation=activation)
            ]
        elif version == 39: # best
            # epoch 0 - 0.76 logloss, 32.6% misclass, slow
            # epoch 1 - 0.66, 28.4%
            # epoch 2 - 0.59, 24.6%
            return [
                Conv((2, self.width, self.width), padding=1, init=init, activation=activation),
                Dropout(keep=0.875),
                Conv((3, 1, 100), padding=1, init=init, activation=activation),
                Dropout(keep=0.9),
                Conv((4, 1, 80), padding=1, init=init, activation=activation),
                Dropout(keep=0.9),
                Conv((3, 1, 100), strides={'str_h': 2, 'str_w': 1}, padding=1, init=init,
                     activation=activation),
                Dropout(keep=0.9),
                Conv((5, 1, 100), strides={'str_h': 2, 'str_w': 1}, padding=1, init=init,
                     activation=activation),
                Dropout(keep=0.9),
                Conv((7, 1, 100), strides={'str_h': 2, 'str_w': 1}, padding=1, init=init,
                     activation=activation)
            ]
        elif version == 40: # excellent, faster, lower mem usage:
            # e0 - 0.76, 34.9%
            # e1 - 0.68, 29.3%
            # e2 - 0.66, 28.5%
            # e3 - 0.61, 25.0%
            # e4 - 0.58, 23.8%
            # e5 - 0.60, 25.1%
            # e6 - 0.56, 23.3%
            return [
                Conv((2, self.width + 1, 100), padding={'pad_h': 1, 'pad_w': 1}, init=init, activation=activation),
                Dropout(keep=0.875),
                Conv((3, 2, 100), padding=1, init=init, activation=activation),
                Dropout(keep=0.9),
                Conv((4, 1, 80), padding=1, init=init, activation=activation),
                Dropout(keep=0.9),
                Conv((3, 1, 100), strides={'str_h': 2, 'str_w': 1}, padding=1, init=init,
                     activation=activation),
                Dropout(keep=0.9),
                Conv((5, 1, 100), strides={'str_h': 2, 'str_w': 1}, padding=1, init=init,
                     activation=activation),
                Dropout(keep=0.9),
                Conv((7, 1, 100), strides={'str_h': 2, 'str_w': 1}, padding=1, init=init,
                     activation=activation)
            ]
        elif version == 41:
            return [
                Conv((2, self.width + 1, 100), padding={'pad_h': 1, 'pad_w': 1}, init=init, activation=activation),
                Dropout(keep=0.875),
                Conv((3, 1, 60), padding=1, init=init, activation=activation),
                Dropout(keep=0.9),
                Conv((4, 1, 50), padding=1, init=init, activation=activation),
                Dropout(keep=0.9),
                Conv((3, 1, 50), strides={'str_h': 2, 'str_w': 1}, padding=1, init=init,
                     activation=activation),
                Dropout(keep=0.9),
                Conv((5, 1, 50), strides={'str_h': 2, 'str_w': 1}, padding=1, init=init,
                     activation=activation),
                Dropout(keep=0.9),
                Conv((7, 2, 80), strides={'str_h': 2, 'str_w': 1}, padding=1, init=init,
                     activation=activation)
            ]
        elif version == 42:
            # e0 - 0.81, 37.0%
            # e1 - 0.68, 29.7%
            # e2 - 0.65, 27.6%
            # e3 - 0.61, 26.2%
            # e4 - 0.58, 24.8%
            # e5 - 0.57, 23.8%
            # e6 - 0.55, 22.9%
            return [
                Conv((2, self.width + 1, 100), padding={'pad_h': 1, 'pad_w': 1}, init=init, activation=activation),
                Dropout(keep=0.875),
                Conv((3, 1, 80), padding=1, init=init, activation=activation),
                Dropout(keep=0.9),
                Conv((4, 1, 80), padding=1, init=init, activation=activation),
                Dropout(keep=0.9),
                Conv((3, 2, 100), strides={'str_h': 2, 'str_w': 1}, padding=0, init=init,
                     activation=activation),
                Dropout(keep=0.9),
                Conv((5, 1, 100), strides={'str_h': 2, 'str_w': 1}, padding=0, init=init,
                     activation=activation),
                Dropout(keep=0.9),
                Conv((7, 1, 80), strides={'str_h': 2, 'str_w': 1}, padding=0, init=init,
                     activation=activation)
            ]
        elif version == 43:
            # e0 - 0.86
            return [
                Conv((2, self.width, self.width), padding={'pad_h': 1, 'pad_w': 0}, init=init, activation=activation),
                Dropout(keep=0.875),
                Conv((3, 1, 100), padding=1, init=init, activation=activation),
                Dropout(keep=0.9),
                Conv((4, 1, 100), padding=1, init=init, activation=activation),
                Dropout(keep=0.9),
                Conv((3, 1, 100), strides={'str_h': 2, 'str_w': 1}, padding=0, init=init,
                     activation=activation),
                Dropout(keep=0.9),
                Conv((5, 1, 100), strides={'str_h': 2, 'str_w': 1}, padding=0, init=init,
                     activation=activation),
                Dropout(keep=0.9),
                Conv((7, 1, 100), strides={'str_h': 2, 'str_w': 1}, padding=0, init=init,
                     activation=activation)
            ]
        elif version == 44:
            # e0 - 0.78, 34.5%
            # e1 - 0.65, 27.1%
            # e2 - 0.62, 26.0%
            # e3 - 0.56, 22.7%
            # e4 - 0.56, 23.7%
            # e5 - 0.54, 21.4%
            # e6 - 0.51, 20.5%
            # e7 - 0.55, 21.2%
            # e8 - 0.53, 20.9%
            return [
                Conv((2, self.width, self.width), padding={'pad_h': 1, 'pad_w': 0}, init=init, activation=activation),
                Dropout(keep=0.875),
                Conv((3, 1, 100), padding=1, init=init, activation=activation),
                Dropout(keep=0.9),
                Conv((4, 1, 100), padding=1, init=init, activation=activation),
                Dropout(keep=0.9),
                Conv((5, 1, 100), strides={'str_h': 2, 'str_w': 1}, padding=0, init=init,
                     activation=activation),
                Dropout(keep=0.9),
                Conv((5, 1, 100), strides={'str_h': 2, 'str_w': 1}, padding=0, init=init,
                     activation=activation),
                Dropout(keep=0.9),
                Conv((5, 1, 100), strides={'str_h': 2, 'str_w': 1}, padding=0, init=init,
                     activation=activation)
            ]
        elif version == 45:
            # e0 - 0.77, 33.7%
            # e1 - 0.66, 27.9%
            # e2 - 0.58, 22.9%
            # e3 - 0.55, 22.4%
            # e4 - 0.54, 22.1%
            # e5 - 0.54, 21.9%
            # e6 - 0.51, 19.9%
            # e7 - 0.55, 21.2%
            # e8 - 0.52, 20.3%
            return [
                Conv((2, self.width, self.width), padding={'pad_h': 1, 'pad_w': 0}, init=init, activation=activation),
                Dropout(keep=0.875),
                Conv((3, 1, 80), padding=1, init=init, activation=activation),
                Dropout(keep=0.9),
                Conv((4, 1, 100), padding=1, init=init, activation=activation),
                Dropout(keep=0.9),
                Conv((5, 1, 100), strides={'str_h': 2, 'str_w': 1}, padding=0, init=init,
                     activation=activation),
                Dropout(keep=0.9),
                Conv((5, 1, 100), strides={'str_h': 2, 'str_w': 1}, padding=0, init=init,
                     activation=activation),
                Dropout(keep=0.9),
                Conv((5, 1, 100), strides={'str_h': 2, 'str_w': 1}, padding=0, init=init,
                     activation=activation)
            ]
        elif version == 46:
            # e0 - 0.78, 34.5%
            # e1 - 0.64, 27.0%
            # e2 - 0.71, 31.1%
            return [
                Conv((2, self.width, self.width), padding={'pad_h': 1, 'pad_w': 0}, init=init, activation=activation),
                Dropout(keep=0.875),
                Conv((3, 1, 80), padding=1, init=init, activation=activation),
                Dropout(keep=0.9),
                Conv((2, 1, 100), padding=1, init=init, activation=activation),
                Dropout(keep=0.9),
                Conv((5, 1, 100), strides={'str_h': 2, 'str_w': 1}, padding=0, init=init,
                     activation=activation),
                Dropout(keep=0.9),
                Conv((5, 1, 100), strides={'str_h': 2, 'str_w': 1}, padding=0, init=init,
                     activation=activation),
                Dropout(keep=0.9),
                Conv((5, 1, 100), strides={'str_h': 2, 'str_w': 1}, padding=0, init=init,
                     activation=activation)
            ]
        elif version == 47:
            # e0 - 0.78, 33.6%
            # e1 - 0.65, 27.8%
            # e2 - 0.63, 26.5%
            # e3 - 0.57, 23.4%
            # e4 - 0.55, 23.1%
            # e5 - 0.59, 23.3%
            return [
                Conv((2, self.width, self.width), padding={'pad_h': 1, 'pad_w': 0}, init=init, activation=activation),
                Dropout(keep=0.875),
                Conv((3, 1, 80), padding={'pad_h': 1, 'pad_w': 0}, init=init, activation=activation),
                Dropout(keep=0.9),
                Conv((4, 1, 120), padding={'pad_h': 1, 'pad_w': 0}, init=init, activation=activation),
                Dropout(keep=0.9),
                Conv((5, 1, 100), strides={'str_h': 2, 'str_w': 1}, padding=0, init=init,
                     activation=activation),
                Dropout(keep=0.9),
                Conv((5, 1, 100), strides={'str_h': 2, 'str_w': 1}, padding=0, init=init,
                     activation=activation),
                Dropout(keep=0.9),
                Conv((5, 1, 100), strides={'str_h': 2, 'str_w': 1}, padding=0, init=init,
                     activation=activation)
            ]
        elif version == 48:
            # e0 - 0.77, 34.1%
            # e1 - 0.68, 28.2%
            # e2 - 0.60, 25.0%
            # e3 - 0.56, 23.1%
            # e4 - 0.54, 21.7%
            # e5 - 0.50, 20.3%
            # e6 - 0.59, 22.5
            # e7 - 0.51, 18.6
            # e8 - 0.53, 18.5
            # e9 - 0.53, 19.3
            # e10 - 0.59, 20.4
            return [
                Conv((2, self.width, self.width), padding={'pad_h': 1, 'pad_w': 0}, init=init, activation=activation),
                Dropout(keep=0.875),
                Conv((3, 1, 80), padding={'pad_h': 1, 'pad_w': 0}, init=init, activation=activation),
                Dropout(keep=0.9),
                Conv((4, 1, 100), padding={'pad_h': 1, 'pad_w': 0}, init=init, activation=activation),
                Dropout(keep=0.9),
                Conv((5, 1, 120), strides={'str_h': 2, 'str_w': 1}, padding=0, init=init,
                     activation=activation),
                Dropout(keep=0.9),
                Conv((5, 1, 100), strides={'str_h': 2, 'str_w': 1}, padding=0, init=init,
                     activation=activation),
                Dropout(keep=0.9),
                Conv((5, 1, 80), strides={'str_h': 2, 'str_w': 1}, padding=0, init=init,
                     activation=activation)
            ]
        elif version == 49:
            # e0 - 0.78, 33.5%
            # e1 - 0.68, 28.7%
            # e2 - 0.67, 28.7%
            # e3 - 0.59, 24.9%
            # e4 - 0.53, 21.6%
            # e5 - 0.51, 20.8%
            # e6 - 0.51, 20.4%
            # e7 - 0.51, 19.2%
            return [
                Conv((2, self.width, self.width), padding={'pad_h': 1, 'pad_w': 0}, init=init, activation=activation),
                Dropout(keep=0.875),
                Conv((3, 1, 100), padding={'pad_h': 1, 'pad_w': 0}, init=init, activation=activation),
                Dropout(keep=0.9),
                Conv((4, 1, 80), padding={'pad_h': 1, 'pad_w': 0}, init=init, activation=activation),
                Dropout(keep=0.9),
                Conv((3, 1, 100), strides={'str_h': 2, 'str_w': 1}, padding=0, init=init,
                     activation=activation),
                Dropout(keep=0.9),
                Conv((5, 1, 100), strides={'str_h': 2, 'str_w': 1}, padding=0, init=init,
                     activation=activation),
                Dropout(keep=0.9),
                Conv((7, 1, 100), strides={'str_h': 2, 'str_w': 1}, padding=0, init=init,
                     activation=activation)
            ]
        elif version == 50:
            # e0 - 0.78, 34.3%
            # e1 - 0.73, 30.8%
            # e2 - 0.59, 24.7%
            # e3 - 0.56, 22.6%
            # e4 - 0.53, 21.4%
            # e5 - 0.50, 20.4%
            # e6 - 0.50, 20.5%
            # e7 - 0.52, 19.9%
            # e8 - 0.53, 18.8%
            return [
                Conv((2, self.width, self.width), padding={'pad_h': 1, 'pad_w': 0}, init=init, activation=activation),
                Dropout(keep=0.85),
                Conv((3, 1, 100), padding={'pad_h': 1, 'pad_w': 0}, init=init, activation=activation),
                Dropout(keep=0.92),
                Conv((4, 1, 80), padding={'pad_h': 1, 'pad_w': 0}, init=init, activation=activation),
                Dropout(keep=0.9),
                Conv((3, 1, 100), strides={'str_h': 2, 'str_w': 1}, padding=0, init=init,
                     activation=activation),
                Dropout(keep=0.9),
                Conv((5, 1, 100), strides={'str_h': 2, 'str_w': 1}, padding=0, init=init,
                     activation=activation),
                Dropout(keep=0.9),
                Conv((7, 1, 100), strides={'str_h': 2, 'str_w': 1}, padding=0, init=init,
                     activation=activation)
            ]
        elif version == 51:
            # e0 - 0.81, 36.4%
            # e1 - 0.70, 30.7%
            # e2 - 0.62, 26.8%
            # e3 - 0.59, 23.8%
            return [
                MergeBroadcast([
                    [
                        Conv((2, self.width, 100), padding={'pad_h': 1, 'pad_w': 0}, init=init,
                             activation=activation),
                        Dropout(keep=0.85),
                        Conv((3, 1, 60), strides={'str_h': 2, 'str_w': 1}, padding=0, init=init,
                             activation=activation),
                        Dropout(keep=0.9),
                        Conv((5, 1, 60), strides={'str_h': 2, 'str_w': 1}, padding=0, init=init,
                             activation=activation),
                        Dropout(keep=0.9),
                        Conv((7, 1, 60), strides={'str_h': 2, 'str_w': 1}, padding=0, init=init,
                             activation=activation)
                    ],
                    [
                        Conv((3, self.width, 100), padding={'pad_h': 1, 'pad_w': 0}, init=init,
                             activation=activation),
                        Dropout(keep=0.85),
                        Conv((3, 1, 60), strides={'str_h': 2, 'str_w': 1}, padding=0, init=init,
                             activation=activation),
                        Dropout(keep=0.9),
                        Conv((5, 1, 60), strides={'str_h': 2, 'str_w': 1}, padding=0, init=init,
                             activation=activation),
                        Dropout(keep=0.9),
                        Conv((7, 1, 60), strides={'str_h': 2, 'str_w': 1}, padding=0, init=init,
                             activation=activation)
                    ],
                    [
                        Conv((4, self.width, 100), padding={'pad_h': 2, 'pad_w': 0}, init=init,
                             activation=activation),
                        Dropout(keep=0.85),
                        Conv((3, 1, 60), strides={'str_h': 2, 'str_w': 1}, padding=0, init=init,
                             activation=activation),
                        Dropout(keep=0.9),
                        Conv((5, 1, 60), strides={'str_h': 2, 'str_w': 1}, padding=0, init=init,
                             activation=activation),
                        Dropout(keep=0.9),
                        Conv((7, 1, 60), strides={'str_h': 2, 'str_w': 1}, padding=0, init=init,
                             activation=activation)
                    ]
                ], 'stack'),
            ]
        elif version == 52:
            # e0 - 0.79, 34.1%
            # e1 - 0.66, 29.9%
            # e2 - 0.63, 26.8%
            return [
                MergeBroadcast([
                    [
                        Conv((2, self.width, 100), padding={'pad_h': 1, 'pad_w': 0}, init=init,
                             activation=activation),
                        Dropout(keep=0.875),
                        Conv((5, 1, 60), strides={'str_h': 2, 'str_w': 1}, padding=0, init=init,
                             activation=activation),
                        Dropout(keep=0.9),
                        Conv((5, 1, 60), strides={'str_h': 2, 'str_w': 1}, padding=0, init=init,
                             activation=activation),
                        Dropout(keep=0.9),
                        Conv((7, 1, 60), strides={'str_h': 2, 'str_w': 1}, padding=0, init=init,
                             activation=activation)
                    ],
                    [
                        Conv((3, self.width, 100), padding={'pad_h': 1, 'pad_w': 0}, init=init,
                             activation=activation),
                        Dropout(keep=0.875),
                        Conv((5, 1, 60), strides={'str_h': 2, 'str_w': 1}, padding=0, init=init,
                             activation=activation),
                        Dropout(keep=0.9),
                        Conv((5, 1, 60), strides={'str_h': 2, 'str_w': 1}, padding=0, init=init,
                             activation=activation),
                        Dropout(keep=0.9),
                        Conv((7, 1, 60), strides={'str_h': 2, 'str_w': 1}, padding=0, init=init,
                             activation=activation)
                    ],
                    [
                        Conv((4, self.width, 100), padding={'pad_h': 1, 'pad_w': 0}, init=init,
                             activation=activation),
                        Dropout(keep=0.875),
                        Conv((5, 1, 60), strides={'str_h': 2, 'str_w': 1}, padding=0, init=init,
                             activation=activation),
                        Dropout(keep=0.9),
                        Conv((5, 1, 60), strides={'str_h': 2, 'str_w': 1}, padding=0, init=init,
                             activation=activation),
                        Dropout(keep=0.9),
                        Conv((7, 1, 60), strides={'str_h': 2, 'str_w': 1}, padding=0, init=init,
                             activation=activation)
                    ]
                ], 'stack'),
            ]
        elif version == 53:
            # e0 - 0.74, 32.8%
            # e1 - 0.65, 27.8%
            # e2 - 0.64, 26.8%
            return [
                MergeBroadcast([
                    [
                        Conv((2, self.width, 100), padding={'pad_h': 1, 'pad_w': 0}, init=init,
                             activation=activation),
                        Dropout(keep=0.875),
                        Affine(100, init=GlorotUniform(), activation=activation)
                    ],
                    [
                        Conv((3, self.width, 100), padding={'pad_h': 1, 'pad_w': 0}, init=init,
                             activation=activation),
                        Dropout(keep=0.875),
                        Affine(100, init=GlorotUniform(), activation=activation)
                    ],
                    [
                        Conv((4, self.width, 100), padding={'pad_h': 1, 'pad_w': 0}, init=init,
                             activation=activation),
                        Dropout(keep=0.875),
                        Affine(100, init=GlorotUniform(), activation=activation)
                    ]
                ], 'stack'),
            ]
        elif version == 54:
            # e0 - 0.74, 32.9%
            # e1 - 0.66, 28.4%
            # e2 - 0.64, 26.9%
            # e3 - 0.60, 25.1%
            # e4 - 0.60, 23.9%
            # e5 - 0.64, 24.4%
            return [
                MergeBroadcast([
                    [
                        Conv((2, self.width, 100), padding={'pad_h': 1, 'pad_w': 0}, init=init,
                             activation=activation),
                        Dropout(keep=0.875),
                        Conv((5, 1, 100), strides={'str_h': 2, 'str_w': 1},
                             padding={'pad_h': 2, 'pad_w': 0}, init=init,
                             activation=activation),
                    ],
                    [
                        Conv((3, self.width, 100), padding={'pad_h': 1, 'pad_w': 0}, init=init,
                             activation=activation),
                        Dropout(keep=0.875),
                        Conv((5, 1, 100), strides={'str_h': 2, 'str_w': 1},
                             padding={'pad_h': 2, 'pad_w': 0}, init=init,
                             activation=activation),
                    ],
                    [
                        Conv((4, self.width, 100), padding={'pad_h': 1, 'pad_w': 0}, init=init,
                             activation=activation),
                        Dropout(keep=0.875),
                        Conv((5, 1, 100), strides={'str_h': 2, 'str_w': 1},
                             padding={'pad_h': 2, 'pad_w': 0}, init=init,
                             activation=activation),
                    ]
                ], 'stack'),
                Dropout(keep=0.8),
                Affine(100, init=GlorotUniform(), activation=activation)
            ]
        elif version == 55:
            # e0 - 0.81, 36.8%
            # e1 - 0.68, 29.4%
            return [
                MergeBroadcast([
                    [
                        Conv((2, self.width, 100), padding={'pad_h': 1, 'pad_w': 0}, init=init,
                             activation=activation),
                        Dropout(keep=0.875),
                        Conv((5, 1, 120), strides={'str_h': 2, 'str_w': 1}, padding=0, init=init,
                             activation=activation),
                        Dropout(keep=0.9),
                        Conv((5, 1, 100), strides={'str_h': 2, 'str_w': 1}, padding=0, init=init,
                             activation=activation),
                        Dropout(keep=0.9),
                        Conv((5, 1, 80), strides={'str_h': 2, 'str_w': 1}, padding=0, init=init,
                             activation=activation)
                    ],
                    [
                        Conv((3, self.width, 100), padding={'pad_h': 1, 'pad_w': 0}, init=init,
                             activation=activation),
                        Dropout(keep=0.875),
                        Conv((5, 1, 120), strides={'str_h': 2, 'str_w': 1}, padding=0, init=init,
                             activation=activation),
                        Dropout(keep=0.9),
                        Conv((5, 1, 100), strides={'str_h': 2, 'str_w': 1}, padding=0, init=init,
                             activation=activation),
                        Dropout(keep=0.9),
                        Conv((5, 1, 80), strides={'str_h': 2, 'str_w': 1}, padding=0, init=init,
                             activation=activation)
                    ],
                    [
                        Conv((4, self.width, 100), padding={'pad_h': 1, 'pad_w': 0}, init=init,
                             activation=activation),
                        Dropout(keep=0.875),
                        Conv((5, 1, 120), strides={'str_h': 2, 'str_w': 1}, padding=0, init=init,
                             activation=activation),
                        Dropout(keep=0.9),
                        Conv((5, 1, 100), strides={'str_h': 2, 'str_w': 1}, padding=0, init=init,
                             activation=activation),
                        Dropout(keep=0.9),
                        Conv((5, 1, 80), strides={'str_h': 2, 'str_w': 1}, padding=0, init=init,
                             activation=activation)
                    ]
                ], 'stack'),
            ]
        elif version == 56: # 56
            # e0 - 0.74, 32.5%
            # e1 - 0.65, 26.9%
            # e2 - 0.59, 24.9%
            # e3 - 0.55, 22.4%
            # e4 - 0.61, 25.1
            # e5 - 0.50, 19.5
            # e5 - 0.54, 19.5
            # e5 - 0.53, 19.1
            return [
                Conv((2, self.width, self.width), padding={'pad_h': 1, 'pad_w': 0}, init=init, activation=activation),
                Dropout(keep=0.875),
                Conv((3, 1, 80), padding={'pad_h': 1, 'pad_w': 0}, init=init, activation=activation),
                Dropout(keep=0.92),
                Conv((4, 1, 120), padding={'pad_h': 1, 'pad_w': 0}, init=init, activation=activation),
                Dropout(keep=0.9),
                Conv((5, 1, 100), strides={'str_h': 2, 'str_w': 1}, padding=0, init=init,
                     activation=activation),
                Dropout(keep=0.9),
                Conv((5, 1, 100), strides={'str_h': 2, 'str_w': 1}, padding=0, init=init,
                     activation=activation),
                Dropout(keep=0.9),
                Conv((5, 1, 80), strides={'str_h': 2, 'str_w': 1}, padding=0, init=init,
                     activation=activation)
            ]
        elif version == 62:
            # e0 - 0.82, 36.6%
            # e1 - 0.68, 28.8%
            # e2 - 0.63, 25.5%
            # e3 - 0.57, 23.6%
            # e4 - 0.55, 24.0%
            # e5 - 0.54, 21.5%
            # e6 - 0.51, 19.7%
            # e7 - 0.53, 20.1%
            # e8 - 0.52, 19.5%
            # e9 - 0.64, 22.8%
            return [
                Dropout(keep=0.9),
                Conv((2, self.width, self.width), padding={'pad_h': 1, 'pad_w': 0}, init=init, activation=activation),
                Dropout(keep=0.9),
                Conv((3, 1, 80), padding={'pad_h': 1, 'pad_w': 0}, init=init, activation=activation),
                Dropout(keep=0.9),
                Conv((4, 1, 100), padding={'pad_h': 1, 'pad_w': 0}, init=init, activation=activation),
                Dropout(keep=0.9),
                Conv((5, 1, 100), strides={'str_h': 2, 'str_w': 1}, padding=0, init=init,
                     activation=activation),
                Dropout(keep=0.9),
                Conv((5, 1, 100), strides={'str_h': 2, 'str_w': 1}, padding=0, init=init,
                     activation=activation),
                Dropout(keep=0.9),
                Conv((5, 1, 80), strides={'str_h': 2, 'str_w': 1}, padding=0, init=init,
                     activation=activation)
            ]
        elif version == 64:
            # e0 - 0.80, 36.1%
            # e1 - 0.65, 27.7%
            # e2 - 0.67, 27.1%
            # e3 - 0.57, 23.4%
            # e4 - 0.55, 22.7%
            # e5 - 0.51, 20.8%
            # e6 - 0.62, 23.7%
            # e7 - 0.62, 22.1%
            # e8 - 0.53, 20.4%
            # e9 - 0.56, 20.2%
            return [
                Noise(noise_pct_std=0.001),
                Dropout(keep=0.95),
                Conv((2, self.width, self.width), padding={'pad_h': 1, 'pad_w': 0}, init=init, activation=activation),
                Dropout(keep=0.875),
                Conv((3, 1, 80), padding={'pad_h': 1, 'pad_w': 0}, init=init, activation=activation),
                Dropout(keep=0.925),
                Conv((4, 1, 100), padding={'pad_h': 1, 'pad_w': 0}, init=init, activation=activation),
                Dropout(keep=0.9),
                Conv((5, 1, 100), strides={'str_h': 2, 'str_w': 1}, padding=0, init=init,
                     activation=activation),
                Dropout(keep=0.9),
                Conv((5, 1, 100), strides={'str_h': 2, 'str_w': 1}, padding=0, init=init,
                     activation=activation),
                Dropout(keep=0.9),
                Conv((5, 1, 80), strides={'str_h': 2, 'str_w': 1}, padding=0, init=init,
                     activation=activation)
            ]
        elif version == 65:
            # e0 - 0.92, 44.2%
            # e1 - 0.68, 28.7%
            # e2 - 0.61, 25.4%
            # e3 - 0.55, 23.4%
            # e - 0., %
            return [
                Conv((2, self.width, int(max(self.width / 2, 100))),
                     padding={'pad_h': 1, 'pad_w': 0}, init=init, activation=activation),
                Dropout(keep=0.9),
                Conv((3, 1, 100), padding={'pad_h': 1, 'pad_w': 0}, init=init, activation=activation),
                Dropout(keep=0.9),
                Conv((4, 1, 100), padding={'pad_h': 1, 'pad_w': 0}, init=init, activation=activation),
                Dropout(keep=0.9),
                Conv((5, 1, 100), strides={'str_h': 2, 'str_w': 1}, padding=0, init=init,
                     activation=activation),
                Dropout(keep=0.9),
                Conv((6, 1, 100), strides={'str_h': 2, 'str_w': 1}, padding=0, init=init,
                     activation=activation),
                Dropout(keep=0.9),
                Conv((5, 1, 80), strides={'str_h': 2, 'str_w': 1}, padding=0, init=init,
                     activation=activation)
            ]
        elif version == 66:
            # e0 - 0.79, 33.9%
            # e1 - 0.64, 26.9%
            # e2 - 0.57, 23.2%
            # e3 - 0.55, 22.2%
            # e4 - 0.51, 20.6%
            # e5 - 0.53, 20.9%
            # e6 - 0.49, 19.5%
            # e7 - 0.51, 19.2%
            # e8 - 0.55, 19.1%
            # e9 - 0.63, 20.7%
            return [
                Noise(noise_pct_std=0.002),
                Conv((2, self.width, self.width), padding={'pad_h': 1, 'pad_w': 0}, init=init, activation=activation),
                Dropout(keep=0.8),
                Conv((3, 1, 100), padding={'pad_h': 1, 'pad_w': 0}, init=init, activation=activation),
                Dropout(keep=0.8),
                Conv((4, 1, 100), padding={'pad_h': 1, 'pad_w': 0}, init=init, activation=activation),
                Dropout(keep=0.8),
                Conv((5, 1, 100), strides={'str_h': 2, 'str_w': 1}, padding=0, init=init,
                     activation=activation),
                Dropout(keep=0.8),
                Conv((5, 1, 100), strides={'str_h': 2, 'str_w': 1}, padding=0, init=init,
                     activation=activation),
                Dropout(keep=0.8),
                Conv((5, 1, 100), strides={'str_h': 2, 'str_w': 1}, padding=0, init=init,
                     activation=activation)
            ]
        elif version == 67:
            # e0 - 0.81, 35.9%
            # e1 - 0.65, 27.4%
            # e2 - 0.61, 25.4%
            # e3 - 0.54, 21.7%
            # e4 - 0.50, 19.9%
            # e5 - 0.53, 21.4%
            # e6 - 0.50, 19.6%
            # e7 - 0.51, 19.9%
            # e8 - 0.53, 19.3%
            # e - 0., %
            return [
                Noise(noise_pct_std=0.001),
                Conv((2, self.width, self.width), padding={'pad_h': 1, 'pad_w': 0},
                     init=init, activation=activation),
                Noise(),
                Dropout(keep=0.875),
                Conv((3, 1, 80), padding={'pad_h': 1, 'pad_w': 0}, init=init, activation=activation),
                Dropout(keep=0.925),
                Conv((4, 1, 100), padding={'pad_h': 1, 'pad_w': 0}, init=init, activation=activation),
                Dropout(keep=0.9),
                Conv((5, 1, 100), strides={'str_h': 2, 'str_w': 1}, padding=0, init=init,
                     activation=activation),
                Dropout(keep=0.9),
                Conv((3, 1, 100), strides={'str_h': 2, 'str_w': 1}, padding=0, init=init,
                     activation=activation),
                Dropout(keep=0.9),
                Conv((7, 1, 80), strides={'str_h': 2, 'str_w': 1}, padding=0, init=init,
                     activation=activation)
            ]
        elif version == 68:
            # * learning rates above were typically 0.0005. this run is 0.001
            # e0 - 0.78, 34.7%
            # e1 - 0.69, 28.8%
            # e2 - 0.55, 21.9%
            # e3 - 0.52, 21.3%
            # e4 - 0.51, 19.6%
            # e5 - 0.51, 19.1%
            # e6 - 0.58, 21.0%
            # e7 - 0.%
            # e8 - 0.%
            # e9 - 0.%
            # e10 - 0.%
            # e11 - 0.%
            # e - 0.%
            # e - 0.%
            # e - 0.%
            return [
                # the embedding type or dimensions may be sensitive to noise_pct_std, which
                # should be evaluated and improved over time
                Noise(noise_pct_std=0.001),
                Conv((2, self.width, self.width), padding={'pad_h': 1, 'pad_w': 0},
                     init=init, activation=activation),
                Noise(),
                Dropout(keep=0.875),
                Conv((3, 1, 80), padding={'pad_h': 1, 'pad_w': 0}, init=init, activation=activation),
                Dropout(keep=0.925),
                Conv((4, 1, 100), padding={'pad_h': 1, 'pad_w': 0}, init=init, activation=activation),
                Noise(),
                Dropout(keep=0.9),
                Conv((5, 1, 100), strides={'str_h': 2, 'str_w': 1}, padding=0, init=init,
                     activation=activation),
                Dropout(keep=0.9),
                Conv((3, 1, 100), strides={'str_h': 2, 'str_w': 1}, padding=0, init=init,
                     activation=activation),
                Dropout(keep=0.9),
                Conv((7, 1, 80), strides={'str_h': 2, 'str_w': 1}, padding=0, init=init,
                     activation=activation)
            ]
        elif version == 69:
            # * learning rates above were typically 0.0005. this run is 0.001
            # e0 - 0.75, 32.3%
            # e1 - 0.63, 26.6%
            # e2 - 0.54, 22.9%
            # e3 - 0.51, 19.8%
            # e4 - 0.51, 20.2%
            # e5 - 0.53, 19.9%
            # e6 - 0.59, 19.1%
            # e7 - 0.60, 22.9%
            # e8 - 0.56, 19.0%
            # e9 - 0.59, 17.7%
            # e - 0.%
            # e - 0.%
            # e - 0.%
            # e - 0.%
            # e - 0.%
            # e - 0.%
            return [
                Conv((2, self.width, self.width), padding={'pad_h': 1, 'pad_w': 0},
                     init=init, activation=activation),
                Noise(),
                Dropout(keep=0.875),
                Conv((3, 1, 80), padding={'pad_h': 1, 'pad_w': 0}, init=init, activation=activation),
                Dropout(keep=0.925),
                Conv((4, 1, 100), padding={'pad_h': 1, 'pad_w': 0}, init=init, activation=activation),
                Noise(),
                Dropout(keep=0.9),
                Conv((5, 1, 100), strides={'str_h': 2, 'str_w': 1}, padding=0, init=init,
                     activation=activation),
                Dropout(keep=0.9),
                Conv((3, 1, 100), strides={'str_h': 2, 'str_w': 1}, padding=0, init=init,
                     activation=activation),
                Dropout(keep=0.9),
                Conv((7, 1, 80), strides={'str_h': 2, 'str_w': 1}, padding=0, init=init,
                     activation=activation)
            ]
        elif version == -1:
            # * learning rates above were typically 0.0005. this run is 0.001
            # e0 - 0.70, 27.0%
            # e1 - 0.62, 25.5%
            # e2 - 0.61, 62, 25.6%
            # e3 - 0.56, 21.3%
            # e4 - 0.52, 21.4%
            # e5 - 0.52, 19.9%
            # e6 - 0.%
            # e9 - 0.%
            # e10 - 0.%
            # e11 - 0.%
            return [
                Conv((2, self.width, self.width), padding={'pad_h': 1, 'pad_w': 0},
                     init=init, activation=activation),
                Noise(noise_pct_std=0.1),
                Dropout(keep=0.875),
                Conv((3, 1, 80), padding={'pad_h': 1, 'pad_w': 0}, init=init, activation=activation),
                Dropout(keep=0.925),
                Conv((4, 1, 100), padding={'pad_h': 1, 'pad_w': 0}, init=init, activation=activation),
                Dropout(keep=0.9),
                Conv((5, 1, 100), strides={'str_h': 2 if self.num_words > 59 else 1,
                                           'str_w': 1}, padding=0, init=init,
                     activation=activation),
                Dropout(keep=0.9),
                Conv((3, 1, 100), strides={'str_h': 2, 'str_w': 1}, padding=0, init=init,
                     activation=activation),
                Dropout(keep=0.9),
                Conv((7, 1, 80), strides={'str_h': 2, 'str_w': 1}, padding=0, init=init,
                     activation=activation)
            ]
